services:
  kfs:
    container_name: kfs
    build:
      context: .
    environment:
      CFLAGS: >-
        -ffreestanding -fno-stack-protector -nodefaultlibs -nostdlib
        -m32 -march=i386 -Wall -Wextra -Werror -MMD -MP -g3
    volumes:
      - .:/kfs
